### ISSUE TITLE
I got the following issue when running the FGM-plate input file . Can you please clarify?

### ISSUE THREAD

**Issue by SurendranMurugesan** [hnrwagner/USDFLD_FGM#1]
USDFLD_cartesian.for(14): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: ) ,
      SUBROUTINE USDFLD(FIELD,STATEV,PNEWDT,DIRECT,T,CELENT,TIME,DTIME,CMNAME,ORNAME,NFIELD,NSTATV,NOEL,NPT,LAYER,KSPT,KSTEP,KINC,ND
------------------------------------------------------------------------------------------------------------------------------------^
.\ABA_PARAM.INC(1): error #6222: This IMPLICIT statement is not positioned correctly within the scoping unit.
      implicit real*8(a-h,o-z)

**Comment by hnrwagner** [comment]
Thanks for reporting this error,

I created a video for this issue:
https://youtu.be/o9Ra61iVyiY

and modified the code at github.

Best Regards
Ronald

**Comment by SurendranMurugesan** [comment]
Thanks, the issue is resolved. It works.
